#!/usr/bin/env bash
# Runs every debug report for one game in pipeline order and stops at the first failure,
# so a missing artifact is reported against the earliest stage that lacks it rather than
# being masked by later errors. All reports land under <results_dir>/debug/<game>/.
#
# Ordering is the pipeline's own: curiosity -> infer -> zeroshot -> attempt -> practice ->
# dataset -> benchmark. Note that debug_curiosity has to load very large pickles and
# debug_zeroshot starts an emulator, so this is not instant on a first run; both cache
# their outputs.

source scripts/core/utils.sh || { echo "Could not source utils"; exit 1; }

declare -A ARGS
REQUIRED_ARGS=()

populate_array DEBUG_MODEL_ESSENTIALS REQUIRED_ARGS
populate_dict DEBUG_MODEL_DEFAULTS ARGS

ARGS["leg"]="both"
ARGS["extra"]="none"
ARGS["n_samples"]=50
ARGS["n_audit"]=40
ARGS["max_gb"]=8.0
ARGS["skip_curiosity"]=false
ARGS["skip_zeroshot"]=false

# --- Argument parsing (copy verbatim) ---
ALLOWED_FLAGS=("${REQUIRED_ARGS[@]}" "${!ARGS[@]}")
USAGE_STR="Usage: $0"
for req in "${REQUIRED_ARGS[@]}"; do
    USAGE_STR+=" --$req <value>"
done
for opt in "${!ARGS[@]}"; do
    if [[ ! " ${REQUIRED_ARGS[*]} " =~ " ${opt} " ]]; then
        if [[ -z "${ARGS[$opt]}" ]]; then
            echo "DEFAULT VALUE OF KEY \"$opt\" CANNOT BE BLANK"; exit 1
        fi
        USAGE_STR+=" [--$opt <value> (default: ${ARGS[$opt]})]"
    fi
done
function usage() { echo "$USAGE_STR"; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --*)
            FLAG=${1#--}
            VALID=false
            for allowed in "${ALLOWED_FLAGS[@]}"; do
                if [[ "$FLAG" == "$allowed" ]]; then VALID=true; break; fi
            done
            if [ "$VALID" = false ]; then echo "Error: Unknown flag --$FLAG"; usage; fi
            ARGS["$FLAG"]="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1"; usage ;;
    esac
done

for req in "${REQUIRED_ARGS[@]}"; do
    if [[ -z "${ARGS[$req]}" ]]; then echo "Error: --$req is required."; FAILED=true; fi
done
if [ "$FAILED" = true ]; then usage; fi
# --- End argument parsing ---

# Print active variables
echo "Script: $0 Active variables:"
for key in "${!ARGS[@]}"; do
    echo "  -$key = ${ARGS[$key]}"
done

# Shared flags every subscript accepts (game, run_name, executor, output_dir,
# model_name). Per-stage extras are appended on the individual calls below.
shared=$(args_to_flags_subset ARGS DEBUG_MODEL_ARG_KEYS)

if [[ "${ARGS["skip_curiosity"]}" == "true" ]]; then
    echo "=== [1/7] curiosity — skipped ==="
else
    echo "=== [1/7] curiosity ==="
    curiosity_args=$(args_to_flags_subset ARGS DEBUG_ARG_KEYS)
    bash scripts/debug/debug_curiosity.sh $curiosity_args --max_gb "${ARGS["max_gb"]}" || exit 1
fi

echo "=== [2/7] infer ==="
bash scripts/debug/debug_infer.sh $shared || exit 1

if [[ "${ARGS["skip_zeroshot"]}" == "true" ]]; then
    echo "=== [3/7] zeroshot — skipped ==="
else
    echo "=== [3/7] zeroshot (starts an emulator) ==="
    bash scripts/debug/debug_zeroshot.sh $shared || exit 1
fi

echo "=== [4/7] attempt ==="
bash scripts/debug/debug_attempt.sh $shared --extra "${ARGS["extra"]}" || exit 1

echo "=== [5/7] practice ==="
bash scripts/debug/debug_practice.sh $shared --leg "${ARGS["leg"]}" --extra "${ARGS["extra"]}" \
    --n_audit "${ARGS["n_audit"]}" || exit 1

echo "=== [6/7] dataset ==="
bash scripts/debug/debug_dataset.sh $shared --leg "${ARGS["leg"]}" --extra "${ARGS["extra"]}" \
    --n_samples "${ARGS["n_samples"]}" || exit 1

echo "=== [7/7] benchmark ==="
bash scripts/debug/debug_benchmark.sh $shared || exit 1

# Index linking whatever was produced, so the folder has one entry point.
debug_root="$results_dir/debug/${ARGS["game"]}"
index="$debug_root/index.md"
{
    echo "# Debug reports — ${ARGS["game"]}"
    echo
    echo "run_name: \`${ARGS["run_name"]}\` · executor: \`${ARGS["executor"]}\` · model: \`${ARGS["model_name"]}\`"
    echo
    echo "Generated by \`scripts/debug/debug_all.sh\` on $(date '+%Y-%m-%d %H:%M')."
    echo
    echo "Pipeline order — each report covers one stage, and the first stage whose numbers"
    echo "look wrong is where to start reading."
    echo
} > "$index"
for report in \
    "curiosity/report.md" \
    "infer/report.md" \
    "zeroshot/report_none.md" \
    "zeroshot/report_zeroshot_with_curiosity.md" \
    "attempt/report.md" \
    "practice/report_curiosity.md" \
    "practice/report_zeroshot.md" \
    "dataset/report_curiosity.md" \
    "dataset/report_zeroshot.md" \
    "benchmark/comparison.md"; do
    [[ -f "$debug_root/$report" ]] && echo "- [$report]($report)" >> "$index"
done
for episodes in "$debug_root"/benchmark/episodes_*.md; do
    [[ -f "$episodes" ]] && echo "- [benchmark/$(basename "$episodes")](benchmark/$(basename "$episodes"))" >> "$index"
done

echo
echo "All debug reports written under $debug_root/"
echo "Index: $index"
