storage_dir: "storage" # Relative to GameBoyRL root. On GPU, set to an absolute path with sufficient space.
env_dir: "setup/.venv/" # Path to the virtual environment. If you have installed the venv in a different location, make sure to change this.
huggingface_repo_namespace: "unused" # Set to your HuggingFace namespace if syncing data
huggingface_repo_name: "unused" # Set to your HuggingFace repo name if syncing data