declare -A TRAIN_STATES

TRAIN_STATES["pokemon_red,trainer_brock_starting"]="trainer_brock"
TRAIN_STATES["pokemon_red,trainer_bug_catcher"]="trainer_bug_catcher_starting_charmander"
TRAIN_STATES["pokemon_red,trainer_lass"]="trainer_lass_starting_charmander"
TRAIN_STATES["pokemon_red,trainer_youngster"]="trainer_youngster_starting_charmander"
TRAIN_STATES["pokemon_red,location_bills_house"]="location_bills_house_complete location_bills_house_complete_1 location_bills_house_complete_2"
TRAIN_STATES["pokemon_red,location_mt_moon"]="location_mt_moon_complete location_mt_moon_starting_charmander location_mt_moon_complete_1 location_mt_moon_complete_2 location_mt_moon_complete_3 location_mt_moon_complete_4"
TRAIN_STATES["pokemon_red,location_pallet_town"]="location_pallet_town_complete location_pallet_town_complete_1 location_pallet_town_complete_2 location_pallet_town_complete_3"
TRAIN_STATES["pokemon_red,location_pewter_city"]="location_pewter_city_complete location_pewter_city_starting_charmander location_pewter_city_complete_1 location_pewter_city_complete_2 location_pewter_city_complete_3"
TRAIN_STATES["pokemon_red,location_route_11"]="location_route_11_complete location_route_11_complete_1 location_route_11_complete_2 location_route_11_complete_3"
TRAIN_STATES["pokemon_red,location_viridian_forest"]="location_viridian_forest_complete location_viridian_forest_starting_charmander location_viridian_forest_starting_charmander_1 location_viridian_forest_starting_charmander_2 location_viridian_forest_starting_charmander_3"
TRAIN_STATES["pokemon_red,location_pewter_pokemart"]="location_pewter_pokemart_starting_charmander location_pewter_pokemart_starting_charmander_1 location_pewter_pokemart_starting_charmander_2 location_pewter_pokemart_starting_charmander_3"

export TRAIN_STATES
